language: csharp
solution: MiscUtil.Compression.Vcdiff.sln
matrix:
  include:
    - dotnet: 2.2.401
      mono: none
      env: DOTNETCORE=true
    - mono: latest
install: ./Build/install.sh
script: ./Build/script.sh