language: csharp
solution: MiscUtil.Compression.Vcdiff.sln
matrix:
  include:
    - dotnet: 2.2.401
      mono: none
      env: DOTNETCORE=true
    - mono: latest
install:
  - bash Build/install.sh
script:
  - bash Build/script.sh